sudo: false
language: java
install: /bin/true
script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn clean install -Dmaven.test.skip=true && mvn clean verify cobertura:cobertura coveralls:report || false'
  - '[ "${TRAVIS_PULL_REQUEST}" = "true" ] && mvn clean install -Dmaven.test.skip=true && mvn clean test || false'
jdk:
- oraclejdk8
- oraclejdk7
cache:
  directories:
  - $HOME/.m2/repository
before_install:
- openssl aes-256-cbc -K $encrypted_a973fe4f8e79_key -iv $encrypted_a973fe4f8e79_iv
  -in config.properties.enc -out src/test/resources/config.properties -d
after_success:
- codecov

notifications:
  email: false

