sudo: false
language: java
install: /bin/true
script: ./travis.sh
jdk:
- oraclejdk8
- oraclejdk7
cache:
  directories:
  - $HOME/.m2/repository
before_install:
- openssl aes-256-cbc -K $encrypted_a973fe4f8e79_key -iv $encrypted_a973fe4f8e79_iv
  -in config.properties.enc -out src/test/resources/config.properties -d

notifications:
  email: false
