language: java
script: mvn test
after_success:
- mvn clean cobertura:cobertura coveralls:report
jdk:
- oraclejdk8
- oraclejdk7
before_install:
- openssl aes-256-cbc -K $encrypted_a973fe4f8e79_key -iv $encrypted_a973fe4f8e79_iv
  -in config.properties.enc -out src/test/resources/config.properties -d
